export let products = [
    {
        id: "1",
        title: "Acer Predator Helios 300",
        price: 1500,
        stock: 10,
        imageUrl: "https://res.cloudinary.com/dl73hi4ir/image/upload/v1728680722/AcerPredatorHelios300_mqg1n8.jpg",
        description: "Una laptop gamer con procesador Intel i7 y gráficos NVIDIA GeForce RTX 3060.",
        category: "notebooks",
    },
    {
        id: "2",
        title: "Apple Mac Mini M1",
        price: 699,
        stock: 8,
        imageUrl: "https://res.cloudinary.com/dl73hi4ir/image/upload/v1728680723/AppleMacMiniM1_a6xmaw.jpg",
        description: "El Mac Mini con el revolucionario chip M1, ideal para trabajos de alto rendimiento.",
        category: "notebooks",
    },
    {
        id: "3",
        title: "Dell XPS 13",
        price: 1200,
        stock: 4,
        imageUrl: "https://res.cloudinary.com/dl73hi4ir/image/upload/v1728680807/DellXPS13_smcbht.jpg",
        description: "Laptop ultraportátil de alto rendimiento con pantalla InfinityEdge y procesador Intel i7.",
        category: "notebooks",
    },
    {
        id: "4",
        title: "iPhone 11",
        price: 599,
        stock: 9,
        imageUrl: "https://res.cloudinary.com/dl73hi4ir/image/upload/v1728680815/iPhone11_npio43.jpg",
        description: "iPhone 11 con chip A13 Bionic y sistema de cámara dual para fotos de calidad profesional.",
        category: "phones",
    },
    {
        id: "5",
        title: "iPhone 12",
        price: 799,
        stock: 12,
        imageUrl: "https://res.cloudinary.com/dl73hi4ir/image/upload/v1728680815/iPhone12_dkwaby.jpg",
        description: "iPhone 12 con pantalla Super Retina XDR y soporte para 5G.",
        category: "phones",
    },
    {
        id: "6",
        title: "iPhone 13",
        price: 999,
        stock: 7,
        imageUrl: "https://res.cloudinary.com/dl73hi4ir/image/upload/v1728680815/iPhone13_mxx0cz.jpg",
        description: "iPhone 13 con cámara mejorada, pantalla OLED y un potente chip A15 Bionic.",
        category: "phones",
    },
    {
        id: "7",
        title: "LG OLED CX 65'",
        price: 2200,
        stock: 5,
        imageUrl: "https://res.cloudinary.com/dl73hi4ir/image/upload/v1728680825/LGOLEDCX65_pzw9an.jpg",
        description: "Televisor OLED de 65 pulgadas con calidad de imagen 4K y tecnología AI Picture Pro.",
        category: "tv",
    },
    {
        id: "8",
        title: "Corsair K95 RGB Platinum",
        price: 199,
        stock: 7,
        imageUrl: "https://res.cloudinary.com/dl73hi4ir/image/upload/v1728680723/CorsairK95RGBPlatinum_gvm7v3.jpg",
        description: "Teclado mecánico RGB con switches Cherry MX y un reposamuñecas desmontable.",
        category: "keyboards",
    },
    {
        id: "9",
        title: "Razer BlackWidow Elite",
        price: 170,
        stock: 10,
        imageUrl: "https://res.cloudinary.com/dl73hi4ir/image/upload/v1728680842/RazerBlackWidowElite_zt9bqq.png",
        description: "Teclado mecánico gamer con switches Razer y retroiluminación RGB.",
        category: "keyboards",
    },
    {
        id: "10",
        title: "Asus ROG Zephyrus G14",
        price: 1800,
        stock: 5,
        imageUrl: "https://res.cloudinary.com/dl73hi4ir/image/upload/v1728680723/AsusROGZephyrusG14_kztach.jpg",
        description: "Una poderosa laptop para gaming con procesador AMD Ryzen 9 y gráficos NVIDIA RTX 2060.",
        category: "notebooks",
    },
];

export default products;